### ISSUE TITLE
Error-LNK2001 after compiled room & plate DSP on WIN10

### ISSUE THREAD

**Issue by xiangxingxing** [michaelwillis/dragonfly-reverb#119]
Hi! I met "error LNK2001 unresolved external symbol " when call DragonflyReverbDSP(double sampleRate) in plugin/dragonfly-**plate**-reverb/DSP  and  plugin/dragonfly-**room**-reverb/DSP , which not show in plugin/dragonfly-**hall**-reverb/DSP  and hall codes compiled successfully .  I suspect  i lack of some .lib file needed by plate or room. However, I‘m unable to resolve the issue with the information available. Sorry to bother you, but can you give me some tips?

**Comment by xiangxingxing** [comment]
fixed by rename DSP class.

**Comment by michaelwillis** [comment]
@xiangxingxing What new name did you give the DSP class? I wonder if this change should be included in the project for other people trying to build on win.

What other steps are you using the build the project? It would be helpful to document the steps for other people, since I have never done the build on Windows.

**Comment by xiangxingxing** [comment]
> @xiangxingxing What new name did you give the DSP class? I wonder if this change should be included in the project for other people trying to build on win.
> 
> What other steps are you using the build the project? It would be helpful to document the steps for other people, since I have never done the build on Windows.

@michaelwillis Hi, i'm sorry for my unclear description before.  Actually, I just buit some necessary files from Directory “freeverb/” and "plugins/" in order to call DragonflyReverbDSP's api in my project. All codes related to UI are excluded and then built successfully in visual studio on win.

On the other hand, if we want to build the dragonfly-reverb project on win, we can't build directly but can use this tool [https://www.msys2.org/](url) to simulate linux environment.

Thank you !

**Comment by michaelwillis** [comment]
@falkTX Is there a better way for Windows users to compile DPF plugins? I think it's very reasonable to expect that they should be able to compile using win-native tools, it seems silly that they have to simulate a Linux environment to get a win build working.

**Comment by falkTX** [comment]
msys2 are native tools, they are not linux binaries

the problem is that windows suuuucks when it comes to providing regular things we are used to in linux like a proper shell and package manager.
dpf supports MSVC now through cmake, but tbqh I have no idea how to go about supporting makefiles on windows without the use of something like msys or cygwin.

microsoft doesnt care to officially support this kind of workflow, preferring the all-in-one IDE and guis. there is not much we can do

**Comment by michaelwillis** [comment]
@xiangxingxing can your document the steps to successfully build these plugins on windows? I would like to include this in the project readme.md so that other people using windows can more easily get involved in development.
