### ISSUE TITLE
3.2.7 no gui with clap in Bitwig on Linux vst3 works

### ISSUE THREAD

**Issue by ralosch** [michaelwillis/dragonfly-reverb#141]
Tank You for clap!

**Comment by falkTX** [comment]
Yeah I noticed that one too late, was testing with Reaper where CLAP works fine.
Was fixed in https://github.com/DISTRHO/DPF/commit/dcee933ef595dc62fa9ea79d9d3cadaf85d0d543 but this didnt make it into the release.

Bitwig seems quite finicky on what it expects plugin UIs to do... Something for next time/release.

@michaelwillis whenever you need to do a new release, just update dpf to get the fix for this issue.

**Comment by michaelwillis** [comment]
Thanks @falkTX, I'll likely be putting out a 3.2.8 release later this week.

**Comment by michaelwillis** [comment]
@falkTX The commit https://github.com/DISTRHO/DPF/commit/dcee933ef595dc62fa9ea79d9d3cadaf85d0d543 is on the `develop` branch, not the `main` branch. Should I always be using `develop`?

**Comment by michaelwillis** [comment]
This is fixed in [3.2.8](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.8)
