### ISSUE TITLE
[master] lv2 urls are inconsistent

### ISSUE THREAD

**Issue by laenzlinger** [michaelwillis/dragonfly-reverb#161]
After building the plugins, installing them I have tried to list them with `lv2ls`

This resulted in:

```
https://github.com/michaelwillis/dragonfly-reverb
urn:dragonfly:early
urn:dragonfly:plate
urn:dragonfly:room
```

Is this inconsistent naming done by intention or should it be aligned?

**Comment by michaelwillis** [comment]
The first one is `https://github.com/michaelwillis/dragonfly-reverb` for backward compatibility. Originally there was only one Dragonfly Reverb plugin with this URI. Later it was renamed to Dragonfly Hall when Dragonfly Room was developed, but I gave it the same URI so that people could upgrade without breaking their existing projects.

**Comment by laenzlinger** [comment]
thanks for clarification and thanks for pointing out, I understand now that its not URLs, just a unique ID
