### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [michaelwillis/dragonfly-reverb#17]
Thanks for making this; it looks and sounds great!

I just packaged it for NixOS, and would like to use the version with @rghvdberg's nice gui.
That is unlikely to get merged, since there are recent released versions available.

**Comment by rghvdberg** [comment]
The GUI isn't ready yet :-)

**Comment by magnetophon** [comment]
@rghvdberg Thanks, I'll be patient then!  ;)
I'm guessing you want the graph in there first?
Anything else before you do a release?

**Comment by michaelwillis** [comment]
@megnetophon Yes, we're trying to finish up the frequency decay graph, just yesterday some of the Ardour developers suggested that we could make it by piping white noise through the DSP and analyzing the results to get an accurate graph instead of just playing connect-the-dots.

Also I see that you made a request for us to expose an "advanced" tab with additional parameters. I'm not opposed to this, we'll see what @rghvdberg thinks.

**Comment by rghvdberg** [comment]
I like the concept of having few (just enough) controls to make a sound.

One solution would be to add the parameters but don't expose them in the
UI, you can access them. via the generic UI provided by the daw.

Casual users will use the GUI and not be distracted by the abundance of
parameters. Power users can use the generic UI.

**Comment by magnetophon** [comment]
That sounds like a good plan for the graph, but wouldn't that cause double cpu usage, at least every time a parameter is changed?  I guess the dataset is too big to cache, isn't it?

re: exposing parameters: I think that's a great solution!
maybe we should discuss it further on the page of that issue?

**Comment by michaelwillis** [comment]
Yes, it will result in increased CPU usage while the parameters are being adjusted, but this plugin is not very CPU intensive, and it is already not suitable for changing parameters during recording or mastering, since there is a scratchy noise that happens if parameters are adjusted while it is processing audio.

**Comment by michaelwillis** [comment]
@magnetophon Done: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.0.9-pre
