### ISSUE TITLE
LinuxVST?

### ISSUE THREAD

**Issue by re23071998** [michaelwillis/dragonfly-reverb#2]
yeah, vst version would be great! :D

**Comment by rghvdberg** [comment]
shouldn't be any problem with DPF :-)

2018-02-14 4:00 GMT+01:00 re23071998 <notifications@github.com>:

**Comment by michaelwillis** [comment]
@re23071998 Yes, my eventual goal is to have VST and LV2 versions for all three major OS platforms... I haven't tested VST but it might "just work", although it would be better after we have made the GUI since apparently the Distrho Plugin Framework doesn't expose presets when compiled to a VST, so we will have to build them in to the GUI.

**Comment by michaelwillis** [comment]
@re23071998 We haven't forgotten this, @rghvdberg has done some major work on implementing a GUI, but then we found that the VST build would regularly crash. I _think_ I have fixed the problem that would crash the VST, but I want to do some more testing before making it an official release.

**Comment by michaelwillis** [comment]
@re23071998 Done: https://github.com/michaelwillis/dragonfly-reverb/releases/download/0.0.9-pre/DragonflyReverb-VST-linux-64-bit-v0.0.9-pre.tgz
