### ISSUE TITLE
What are Diffuse, Spin and Wander options for?

### ISSUE THREAD

**Issue by unfa** [michaelwillis/dragonfly-reverb#30]
I can't figure out  what these control really do:

![selection_999 536](https://user-images.githubusercontent.com/491704/47367605-4c8b0e00-d6e0-11e8-9a54-43f54c6e5338.png)

I couldn't find any readme.

**Comment by michaelwillis** [comment]
Hi @unfa! I'm glad that you're trying out this plugin, I have really enjoyed watching your demo/tutorial videos. To be honest, I don't completely know how these parameters work either, since I didn't write the algorithm, mostly my plugin just passes them through to Freeverb3. These are all parameters on the late reflection algorithm. Here is my understanding:

* Diffuse

Think of this as how many reflective surfaces are in the reverb space. Lower settings would be more like a more "empty" space, resulting in a more granular sound with fewer reflections. Higher settings should result in a more thick reverb, with more reflections and a more blended sound. I wrote the author of freeverb3, and was told that lower diffuse is better for percussive sounds, higher is better for things that you want more blended.

* Spin / Wander

I have been trying to understand this for a long time. Here is what Freeverb3's docs say:

    * Spin: The frequency of the output chorus.
    * Wander: The length of the output chorus.

That didn't help much. I can tell you what I *think* they do:

The reverb tail is composed of several different delay lines. Let's say that the delay lines would be exactly 50ms apart if there were no wander algorithm. That same reverb with a 10ms wander will modulate the delays such that they can be anywhere from 40ms to 60ms apart.

So instead of having delays at precisely 50ms, 100ms, 150ms, 200ms, and so on, it might instead have something like 48ms, 104ms, 147ms, 201ms...

The spin is a LFO that makes each delay fluctuate. Given that same wander setting described above, the spin would prevent always getting the exact same delays 48ms, 104ms, 147ms, 201ms, etc., instead they will have different numbers every time they are engaged, and the spin parameter is the rate of change.

Again, I could be very wrong, but that is my best guess. The design of these algorithms is highly influenced by the Lexicon hardware reverbs. You can read their description of spin and wander on page 54 of this manual: http://freeverb3vst.osdn.jp/doc/Lexicon/lexicon_480l.pdf

**Comment by unfa** [comment]
Thank you! I might try to use a spectrograph and some test signals to see what is really happening.

I was actually told to check this reverb out by someone, and I really like it!

I could only hear a real difference with the Diffuse parameter, the Wander and Spin were a total mystery. I've heard some reverbs use Chorus algorithms inside to spice up the sound (TAL Reverb III has that very audible).

**Comment by michaelwillis** [comment]
@unfa Please try the new release: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.5

It gives Spin and Wander parameters more extreme range, which makes it easier to understand what they do. Try a very large room size, and set Wander to 0.0 ms, which makes it clear that Spin is an oscillator that moves the reverb tail left and right in the stereo space. Then turn up wander a little bit at a time and you'll find that it modulates the spin per delay line, such that there are multiple sounds moving around at different places in the left/right stereo space.

**Comment by michaelwillis** [comment]
These parameters are now properly documented here:

https://michaelwillis.github.io/dragonfly-reverb/dragonfly-hall-manual.html

Also, the new `modulation` parameter can be set to 100% to better hear the effect of Spin and Wander, then dialed back down to an appropriate level after they are set.
