### ISSUE TITLE
Add sharp lowpass/highpass filter pairs

### ISSUE THREAD

**Issue by unfa** [michaelwillis/dragonfly-reverb#31]
One thing I miss in Dragonfly Reverb is a 24 dB/oct highpass + lowpass filter pair on the wet channel for total spectrum control (useful for bass and drums).

Maybe it could be integrated into the mixer - if each channel (dry, early, tail) had that - it'd be a very powerful functionality.

Making processors sound realistic is cool, but going beyond that is very useful for sound design :)

What do you think?

**Comment by michaelwillis** [comment]
Hi again @unfa! These are some great ideas (including the suggestion you made in the other issue). To give you some background, I wanted a nice concert-hall style plugin on Linux for acoustic instruments, and I didn't find an native one that I liked. I was using falktx's win vst bridge to run the windows version of Freeverb3 Hibiki. I liked the sound, but the interface was hard to use and I really wanted to run a native plugin, so that is why I started working on Dragonfly. I lifted the algorithm from Hibiki, got it working on Linux, and Rob van den Burg made the initial user interface.

http://freeverb3vst.osdn.jp/
http://freeverb3vst.osdn.jp/tutorial/tutorial_vst_hibiki.shtml

I made virtually no change to the reverb algorithms, and that includes the high cut and low cut parameters which came built in to the freeverb3 code. I did consolidate them to make the interface more simple; hibiki has early low pass, early high pass, late low pass, and late high pass. Dragonfly sets them the same for early and late. I do agree that I wish these parameters would cut more decibels than they currently do, so I might dig into the freeverb code and see what I can do about that.

I'm really close to what I wanted in this plugin, which is a simple way to add a nice hall reverb sound to something like a piano arrangement or a woodwind duet or a virtual orchestra. I want to make a 1.0 release for this purpose. What would you think of working together on a separate reverb plugin (or maybe an "advanced" view on this one) for people like you who do electronica and sound design?

**Comment by unfa** [comment]
@michaelwillis Sorry for my extreme latency - I think making a reverb unit tailored for electronic music could be an interesting goal.

I guess it'd require a few more ideas, but I'm sure we could come up with something awesome!

Let me know if you're still willing to do this :)

**Comment by michaelwillis** [comment]
@unfa Yes! My friend told me that I should make an advanced effects plugin and call it `Dragonfly Nights`. I have a lot of ideas, but nothing solid right now. Sometimes I imagine making it modular, kind of like Rakarrack, in which the modules could be effects like delay, low pass, high pass, early reflections, hall reverb, room reverb, etc.

After thinking about that, I then wonder if it would be reinventing the signal routing that belongs in the DAW, in which case it might be better to just make several small plugins, each with a very specific purpose.

Anyway, yes I'm interested, but I'm not sure quite what I want it to be. Let's definitely pressure this. We should find a better means of collaboration than comments in a GitHub issue.

**Comment by unfa** [comment]
Sure! Could you contact we via e-mail?
![Screenshot_20190623_230634](https://user-images.githubusercontent.com/491704/59981957-8fa0d680-960b-11e9-8c47-4cd8b3105fa6.png)
