### ISSUE TITLE
High-decibel noise

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#37]
Some users have reported that Dragonfly Reverb will occasionally exhibit a bug in which it blasts high-decibel noise. For anybody that experiences this bug, please report details here, including OS, DAW, CPU, and any other information that you think might be helpful.

**Comment by suedwestlicht** [comment]
I think we have three observable but hard to reproduce issues at least with the lv2 plugin version:

1. White spectrum display. Can sometimes be cured by opening the GUI several times.
2. High (realtime) CPU load from time to time, causes stuttering sound. Can be cured by reloading the (Qtractor) session.
3. Max output of something (max meter level) that can't be heard because the complete sound is killed. Can be cured by reloading the (Qtractor) session.

I suspect either some uninitialized  parm that causes all of these effects. It may be a race condition in the plugin host as well but that sould be detectable by writing out error messages when enything fails during the init phase. I am no plugin programmer. I hope that such an initialization code exists.

**Comment by michaelwillis** [comment]
@suedwestlicht Thanks for the report. Will you try the VST plugin to see if you experience the same bug? Based on my own experience, I'm starting to wonder if this bug only happens with the LV2 plugin.

**Comment by suedwestlicht** [comment]
I am working with the VST versioin now in Qtractor.

I had the "white display" syndrome twice.

The noise/soundkill-syndrome didn't happen yet. I'll investigate it further.

**Comment by suedwestlicht** [comment]
By now I had only the "white display" syndrome with the VST version, not the noise/soundkill syndrome.

I'll proceed now with one LV2 instance and one VST instance.

**Comment by suedwestlicht** [comment]
On 3 different machines no audio problems yet when using one lv2 and one vst instance in a Qtractor project.

The white display syndrome is still there. Seems to be format-independent.

**Comment by betodealmeida** [comment]
I had the noise issue a few times, since I'm using the plugin on two buses in my template. Unfortunately I can't repro it: sometimes when I open an Ardour project it will blast noise. If I close and load it again, it works fine.

I'm running Arch Linux, Ardour 5.12 (from AUR), with a realtime kernel:

```
Linux nuku 4.16.15-rt7-1-rt #1 SMP PREEMPT RT Wed Jul 4 12:49:06 PDT 2018 x86_64 GNU/Linux
```

**Comment by betodealmeida** [comment]
BTW, @suedwestlicht mentioned a race condition. All my project files have more than one Dragonfly Reverb plugin, so maybe it could be because of that?

**Comment by suedwestlicht** [comment]
Yes, since I have NO noise problem when I have one lv2- and one vst-instance loaded, or two vst-instances. It must be related to having more than one lv2-instance loaded.

**Comment by michaelwillis** [comment]
@betodealmeida Are you using the LV2 or VST version?

**Comment by betodealmeida** [comment]
@michaelwillis I'm using LV2, from Arch's repo: https://www.archlinux.org/packages/community/x86_64/dragonfly-reverb/

**Comment by michaelwillis** [comment]
@betodealmeida Please try using the VST and let me know if you still experience the problem. Meanwhile I am trying to determine a way to fix the LV2.

**Comment by betodealmeida** [comment]
Cool, I'll give VST a try, and I'll let you know if the problem stops. Thanks!

**Comment by michaelwillis** [comment]
@suedwestlicht Would you mind trying to reproduce this on the latest beta release? I have not been able to reproduce the loud feedback noise or the full white spectrogram bug since replacing the FFT algorithm used by the spectrogram (e44ce34). It is possible that this is fixed now.

**Comment by suedwestlicht** [comment]
Looks good.

**Comment by michaelwillis** [comment]
@suedwestlicht `Looks good`? You mean the bug is gone? Or you like the new color scheme? :wink:

**Comment by suedwestlicht** [comment]
Bugs are gone. No white spectrogram and no problems with 2 LV2-instances in one Qtractor session. Tested on Xubuntu 14.04 and16.04.

**Comment by michaelwillis** [comment]
That's great to hear! This bug has been a thorn in my side for a long time.

**Comment by serdeman** [comment]
This same issue just happened to me a few nights ago.  Mixing on headphones.  a VERY bad experience!  WOW.
After looking into this, is it possible that my version of these plugins had the bug?  I was using lv2 V3.0.0.  I just installed V3.2.0.  Should I be safe now?

I'm running Linux Mint 19.  DAW is Ardour 6.2.0.  Intel i5 laptop with 16 Gig ram.

**Comment by michaelwillis** [comment]
@serdeman V3.2.0 does not fix this bug. I thought I had this one resolved a while ago, but it is back with a vengeance. I agree that it is a horrible experience. I still do not know what causes it, and I have no estimate of when it will be fixed.

**Comment by serdeman** [comment]
Hi Michael,

Thank you for helping all of us with this.  When this happened to me, I 
only had one instance of the lv2 pluging.  It was on a buss with only 
one stereo channel's aux send to it.  My "fix" was to delete the plugin 
from the buss, and then add it back in.  Then all was well.  I did not 
have to close the DAW.

Is there a way to make a debug version of the plugin, such that when 
this happens, we can somehow dump a state file for you? In other words, 
I'm here to help in any way I can.  I just need to know how to help.

Yours,

-Steve

**Comment by michaelwillis** [comment]
@serdeman Understood. I previously fixed an issue in which this was a common bug when running multiple instances of the plugin, but I think we're now dealing with a different bug that has the same symptoms.

Do you use the `Shuttle Speed Control` in Ardour's [Transport Bar](https://manual.ardour.org/ardours-interface/the-transport-bar/)? The reason I ask is that I haven't experienced this bug for months, maybe more than a year. Today I started using that control for the first time, and later Dragonfly Room exploded on me. I'm wondering if these plugins have a bug related to the host changing the sample rate or the size of the audio buffer that is shared with the plugin. If I'm onto something here, I'll have to get more info from the Ardour devs about how it behaves differently in regards to that control and how it integrates with plugins.

**Comment by serdeman** [comment]
No.  I don't use shuttle.  Play and stop.  That's me.  I opened the 
session that I had previously worked on.  And hit play right after 
opening.  The issue happened right then.  I was doing nothing else.

**Comment by michaelwillis** [comment]
Aww... in the words of my father, "shot that idea right out of the sky". It really did this right after opening the session? I'm really stumped about this. Has this happened to you more than once?

**Comment by serdeman** [comment]
HAHA. No.  This has never happened to me before.  I am a new user of 
your plugins.  So, I've only used them on a couple sessions. So far, as 
I'm still working on the session where it happened, It has not done it 
again.

**Comment by michaelwillis** [comment]
@serdeman Ok, thanks for letting me know. Robin gave me some good clues on the Ardour forum, I didn't realize (or maybe I just forgot) that Ardour uses the same buffer for input and output on plugins, I'll have to double check what the Dragonfly plugins do with the buffers.

**Comment by serdeman** [comment]
Perfect. You're getting closer...I can feel it!!!

**Comment by michaelwillis** [comment]
@serdeman Do you use any dragonfly plugins other than Room?

**Comment by serdeman** [comment]
Yes. On this particulate session in question, I have one other verb.  
It's the Plate.  On other sessions, I've used the early reflection unit, 
along with the plate.

**Comment by maxxatgit** [comment]
I'm running VST version 3 from KXStudio in Reaper on Ubuntu 19.10. This has been happening off and on for a long time. Reaper will automatically mute a channel with high levels, so I never get my ears blasted. I think it happens when I first open a project. I'll hit the play button and there is no reverb. I'll check the reverb channel/buss, and it will be muted. I just close the project and re-open it. Occasionally, I have to close and re-open the project several times.

Multiple instances don't make any difference. I was editing a template today, and when I opened it... no reverb. That template only has one instance. I have one particular project with a great verb on the snare (one of my drumset templates is based off that project) that has more than one Dragonfly Room instances, and it has happened in that project as well.

One other piece of info; in the project mentioned above, one instance is as a buss reverb, the dry signal is off, 100% wet coming out of the verb. The other instance is inline in an instrument channel so it outputs a wet/dry mix. The problem only happens when used as a 100% wet reverb buss.

I want to thank you Michael, the Dragonfly Reverbs are superb! I use them _all the time_ .

If there is anything I can do to assist you, please let me know.
-Paul

**Comment by spectromas** [comment]
I am also getting this in Reaper with Room and, as mentioned above, I never hear it because the channel gets automuted. I'd be happy to provide any information but not sure what to add to the reports already here, I'm using the version in kxstudio repo in latest reaper on Neon.

**Comment by michaelwillis** [comment]
@maxxatgit @spectromas Thanks for your reports. I'm working on a v4 release of dragonfly reverb that will hopefully address this issue. I'm not sure which version is available from kxstudio, but you can try downloading v3.2.1 from GitHub and see if it is more stable.

**Comment by maxxatgit** [comment]
I just installed v3.2.1 from GitHub. I'll report back if I have issues. 

Although this is occasionally annoying, I still use these reverbs all the time. It maybe takes 30 seconds of fiddling and reopening a project, and I'm good to go. It only happens when opening a saved project. 

I _really_ like these reverbs! I am _very_ grateful that you share this great software with the world. Thank you!

**Comment by spectromas** [comment]
This doesn't appear to have solved it for me, I'm still getting the same thing.

**Comment by michaelwillis** [comment]
@spectromas Thanks for letting me know. Please stay tuned for news on Dragonfly Reverb 4.

**Comment by tassyv** [comment]
Just for the record, I've recently experienced it with Dragonfly Plate and Room reverbs v3.2.1 on Ardour 5.12

**Comment by maxxatgit** [comment]
Just a quick update, I did download and install v3.2.1 and the problem persists. It just happened again a couple of days ago. I had to close and re-open the project, and then everything was good.

**Comment by michaelwillis** [comment]
Please download version 3.2.3 and observe whether the bug still happens:

https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.3

This new release fixes a long-standing bug in which sliders/dials set to zero could result in the plugins failing to initialize properly upon loading. This could result in all sorts of havoc, including the explosion of noise that some people have reported.

**Comment by maxxatgit** [comment]
I finally got around to installing version 3.2.3 about a week ago. I have not had any more issues since then. I think you may have vanquished the bug!

Touche!

Thanks again for this amazing reverb!

**Comment by michaelwillis** [comment]
@maxxatgit Great success! It is so good to have finally cracked this old chestnut.
