### ISSUE TITLE
Optimize CPU usage when idle

### ISSUE THREAD

**Issue by azuwis** [michaelwillis/dragonfly-reverb#57]
Dragonfly Reverb uses 20% CPU per instance in Ardour when idle.

1) Create a new empty session in Ardour
2) Create a MIDI track, `top` show Ardour uses 5% CPU
3) Add 1 Dragonfly Hall Reverb to the MIDI track, Ardour uses 25% CPU
4) Add 1 more Dragonfly Hall Reverb to the MIDI track, Ardour uses 45% CPU
5) Add 1 more Dragonfly Hall Reverb to the MIDI track, Ardour uses 65% CPU

All when Ardour is idle. Is there a way to optimize this?

**Comment by michaelwillis** [comment]
@azuwis Which release are you using? An earlier version had a bug that caused high CPU use. Also, what is your CPU model?

**Comment by azuwis** [comment]
I'm using commit cb562e5, from http://download.tuxfamily.org/librazik/decepas/pool/main/d/dragonfly-reverb/, but compile the deb myself on Debian Sid(Unstable).

CPU is Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz.

**Comment by SpotlightKid** [comment]
I'm experiencing the same high DSP load. A Carla project with a simple monosynth, YKChorus, a delay and ZynReverb in series has 11-12% DSP load. The same project with ZynReverb replaced with Dragonfly Hall has 20% DSP load.

I compiled dragonfly-reverb from the current git (16bcb09) and I have a Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz.

**Comment by michaelwillis** [comment]
@SpotlightKid How heavy is the CPU usage when the the plugin is getting audio input as compared to when the input is "idle"?

**Comment by SpotlightKid** [comment]
It only varies by 1% between 19% and 20% regardless of audio input or not.

Please note that I'm taking about DSP load as displayed in Carla, which I think is the percentage of available processing time per audio frame used, I think.

**Comment by michaelwillis** [comment]
I know it's been quite a while since this bug was reported, but in case it is helpful to anybody, Mattias Westlund found a way to work around the bug as he experienced it:

http://scoringcentral.mattiaswestlund.net/showthread.php?tid=838&pid=6148#pid6148

He found that his DAW reported higher CPU when the reverb plugins weren't getting any input, so he put a -100dB whitenoise generator plugin before dragonfly reverb and the high CPU usage disappeared. It's weird, it's a hack, but it worked for him.

**Comment by michaelwillis** [comment]
@azuwis and @SpotlightKid, please try version 3.2.0 and let me know if you still experience high CPU load while idle.

**Comment by SpotlightKid** [comment]
This is what I observe with version 3.2.0 (compiled from git. same setup as described above):

* If I add dragonfly-hall (LV2) to an empty Carla project, as long as it is not connected to anything, the DSP load is about 3% (the normal idle load on my system).
* As soon as I connect anything to the inputs (e.g. two inputs from my audio interface, so no additional plugins are loaded), the DSP load goes up to 12-13% and stays that way.
* If I disconnect the audio inputs again, the DSP load nevertheless stays around 12-13%.

**Comment by Tremeschin** [comment]
I have this issue, even [reported it wrongly](https://github.com/DISTRHO/DISTRHO-Ports/issues/57), thought it was TAL Filter 2 shenanigans, turns out I use both TAL and Dragonfly together and because TAL takes a bit to load the GUI whilst Dragonfly opens quickly, I thought it was the other plugin with high DSP usage.

Now when I put 10 instances of Dragonfly Room the audio starts to crackle on Ardour, have to use 4096 samples at least on big projects of mine.

- I don't have this issue with Dragonfly Hall, 10 instances doesn't crackle the audio and have some pretty moderate CPU usage for them.

- Tested both `dragonfly-reverb` and `dragonfly-reverb-git` on Arch repos, both have this same issue on Dragonfly Room (only?), Hall seems to be fine.

- Same issue happens on ALSA, Jack Audio (`jack` and `jack2`) on low-enough buffer size per Dragonfly instance count

As some suggested like @michaelwillis , unfortunately for me adding a white noise before Dragonfly Reverb does not fix the issue for me.

**Comment by michaelwillis** [comment]
Please try version 3.2.3 and report back the CPU usage:

https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.3

**Comment by tctimmeh** [comment]
Just want to note that this problem still exists, as well as maxing out DSP when the project is loaded with more than one dragonfly active.

I am using Dragonly v3.2.5 in Ardour 6.9 on Ubuntu 22.04.

**Comment by unxs0** [comment]
Problem still exists for both vst and lv2: Ubuntu 22.04 and Ardour 6.9. 100% at idle! (Awesome reverb!)

**Comment by michaelwillis** [comment]
@unxs0 What version of dragonfly reverb are you using?

**Comment by michaelwillis** [comment]
[Release 3.2.10](https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.10) has denormal protection that covers all of the DSP code, which should mitigate this issue.
