### ISSUE TITLE
Not working in MacOS Catalina 

### ISSUE THREAD

**Issue by ghost** [michaelwillis/dragonfly-reverb#70]
Hello, I just downloaded MacOS version of all Dragonfly Reverb plugins and it doesn't load in any daw on MacOS Catalina, I tried to allow it in the Security tab in System Preferences, but it seems that it won't work with .vst files.

**Comment by michaelwillis** [comment]
This is a known problem with many audio plugins in Catalina: https://cdm.link/2019/09/macos-catalina-will-be-incompatible-with-much-of-your-music-software-heres-what-to-know

The short story is that you can disable the security feature that is blocking Dragonfly Reverb by running the following from the command line:

`sudo spctl --master-disable`

Please understand that this is not recommended, it is just a way to work around the problem. Hopefully in the future Dragonfly Reverb can be notarized to work on Catalina, but I can't make any promised right now.

**Comment by falkTX** [comment]
There is no need to notarize the plugins, at least not yet. We "just" need to make an installer for it. The user still needs to right-click the installer and use open from there (instead of direct double-clicking), but at least this avoid the user having to run things on the CLI.

Feel free to copy from https://github.com/falkTX/Carla/commit/e1d0ecf003cd8188d6937e22a62722bd5aecbd86 where I added a way to create a package file for the carla plugin version.

**Comment by t6d** [comment]
Another, less aggressive, workaround is to remove the quarantine flag from the `*.vst` files once they've been moved to `/Library/Audio/Plug-Ins/VST`. Simply run,

```bash
xattr -d com.apple.quarantine /Library/Audio/Plug-Ins/VST/Dragonfly*.vst
```

to fix the loading issue.

**Comment by michaelwillis** [comment]
The new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6) now has a proper MacOS universal installer. Download the MacOS version, open up the zip file, right-click on `dragonfly-reverb-macOS.pkg`, and select `open`. It will give you a warning dialog that the developer can't be verified, but you can still open to `Open`. It will launch the installer and then you will be able to run the plugins from your DAW without them being quarantined by MacOS security.
