### ISSUE TITLE
Dragonfly Plate and Surge?

### ISSUE THREAD

**Issue by mkruselj** [michaelwillis/dragonfly-reverb#94]
Hi!

I'm one of the maintainers of [Surge synthesizer](https://surge-synthesizer.github.io/).

We were chatting about expanding our FX and realized that Dragonfly reverbs could fit very nicely into Surge. Surge is FOSS GPL3 software, so from a licensing perspective on the engine I think we are good. But before we do that, we wanted to check a couple of things:

1. Even though it's all GPL3 and we could do it, doesn't mean you would want us to. Any objections or concerns?
2. If we do include your reverbs (we would start with Plate, since currently it's the only one that fits based on parameter count, right now a Surge effect can have no more than 12 parameters due to internal limitations we need to remove at some point), is there a way you would like us to name the FX or credit you in a way that would be appropriate? Basically, do you have any concerns regarding us keeping the name Dragonfly Plate, or renaming it to something that might fit better in Surge (currently we have Reverb 1 and Reverb 2, which are quite generic - so renaming Dragonfly Plate to just Plate Reverb seems appropriate, but we won't do it if you don't want us to).

In our 1.8.0 release we imported 50+ Airwindows FX into Surge after chatting with Chris, for instance, and pulled in the filters from OB-Xd, and ended up putting them in the plugin's about page as below.

![image](https://user-images.githubusercontent.com/2393720/108686198-5e219200-74f5-11eb-8381-b86d8cc8199d.png)

In any case, thanks for making great open source audio tools and for considering this issue!

Best

**Comment by michaelwillis** [comment]
I don't have a problem with you repurposing dragonfly reverb to include in
surge. The dragonfly plugins are mostly just wrappers for the freeverb3
library, so it might be more simple for you to use just the library instead
of the dragonfly source code.

Part of the reason that the room and hall effects have so many parameters
is that they both include the early reflections algorithm. If you separate
that out as a stand-alone effect, I think you could probably narrow down
the room and hall effects to twelve parameter without hobbling their
capabilities. I haven't looked at how you do presets with surge, but if you
can set them up so that the early refections effect has a little bit of
send to the room or hall effect, that would end up doing what dragonfly
room and hall already do.

Cheers,
Michael

**Comment by mkruselj** [comment]
Thank you!

Thanks for the pointers as well regarding direct freeverb3 implementation and ER/LR separation. The latter might be a bit tricky because we're currently relatively limited by the number of FX slots (2 per scene, 2 sends, 2 total FX), so personally I would just like to have the whole algorithm as is in Dragonfly plugins - and we can tear off the ER algo anyways into a separate effect, for those who want to have a play with that. 🙂

**Comment by michaelwillis** [comment]
Awesome! I'm always glad to see more reverb happening in other projects.

I can make a few recommendations on how to incorporate the room and hall
reverbs, in order to cut them down to 12 parameters:

For the room reverb, keep the size, predelay, decay, diffuse, spin, and
wander. Consolidate early damp and late damp into a single "Damp"
parameter. The bass boost effect (low boost and boost freq dials) is
honestly kind of bogus, and you can probably get rid of both high cut and
low cut, all four of the above would probably be better done with a
separate EQ effect. Early Level, Early Send, and Late Level would probably
be better represented as decibels instead of percentage, and if I were to
do it all over again I would replace Dry Level with a wet/dry mix parameter
instead. So that's 11 parameters for the room, I guess 12 if you want to
keep the two dampers separate.

Hall is harder to pare down, I actually find all of the dials useful to
some extent. You could get rid of all of the "High..." and "Low..." dials,
but I feel like the crossovers and multipliers are actually an important
part of dragonfly hall's signature sound. Still, you could set them at some
reasonable default and not expose them, and I think you would still get a
decent sound.

Let me know how it goes!

Cheers,
Michael

**Comment by mkruselj** [comment]
In Surge we always do dry-wet mix as a single parameter, so that would already be a thing 🙂

But yeah, I think it makes sense to just not pare down the "biggies" here, once we can have more than 12 params per FX (which should be later this year), we can add the rest. For now, it's gonna be the plate and the ER algo, I'd say.

Thanks for your input, it's appreciated! Gonna close this issue since the initial question has been resolved, but feel free to continue the chat if you want, or also take a look into Surge codebase/issue tracker if you're so inclined. We never say no to extra hands 🙂
